### ISSUE TITLE
How much GPU memory will be cost?

### ISSUE THREAD

**Issue by kxhit** [sshaoshuai/PointRCNN#1]
I read your paper and notice that you use 4 set-abstraction layers with multi-scale grouping (with sizes 4096, 1024, 256, 64) and subsample 16,384 points from each scene as the inputs. I think this is very consuming and want to know how much GPU memory will be used. Thanks!

**Comment by sshaoshuai** [comment]
Actually it doesn't cost too much memory. A single 12GB GPU is enough for the training of the RPN stage and RCNN stage, and more GPUs could speed up the training process.
Code will be released soon and you could run it yourself for more details. 
Thanks!
