### ISSUE TITLE
About the network output coordinate

### ISSUE THREAD

**Issue by muzi2045** [sshaoshuai/PointRCNN#102]
I have tried to looking into the origin output of the network, such as:
```  
 input_data = {"pts_input": self.inputs}
 ret_dict = self.net(input_data)       
 roi_scores_raw = ret_dict['roi_scores_raw']
 roi_boxes3d = ret_dict['rois']     # (B, M, 7)
 seg_result = ret_dict['seg_result'].long()
```
without nms-gpu or scores filter
Visualization in ros rviz , the boundingbox position look really strange
![image](https://user-images.githubusercontent.com/12984898/64325526-ea3ab380-cffa-11e9-9ff0-1db4ef19eab6.png)
Are the boxes in the  kitti camera coordinate or in the lidar coordinate?
hopefully for any advice 
@sshaoshuai

**Comment by bmankirLinker** [comment]
The input/output of the PRCNN trained by KITTI is in camera coordinates since KITTI ground truth 3d cuboids are in camera coordinates, thus you gotta transform to the velo coordinates if you wanna visualize in velo domain.

**Comment by seboz123** [comment]
@muzi2045 Have you managed to visualize the output in rviz in the lidar coordinate system?

**Comment by muzi2045** [comment]
just convert the output boxes in camera coords to lidar coords, it can be normally visualized.

**Comment by zhanghm1995** [comment]
@muzi2045 Hi, how did you visualize the results in Rviz? Using the python version RViz or some other methods？
