### ISSUE TITLE
problem when compiling iou3d and roipool3d in Windows

### ISSUE THREAD

**Issue by lonely7yk** [sshaoshuai/PointRCNN#103]
I have compiled the codes of iou3d and roipool3d in Ubuntu successfully, but when I tried to compiled iou3d in Windows, the error occurred that showed 'identifier "EPS" is undefined in device code'. Thus, I change the code like below.

```cpp
//#define DEBUG
const int THREADS_PER_BLOCK_NMS = sizeof(unsigned long long) * 8;
//const float EPS = 1e-8;
#define EPS 1e-8
```

However, I met another problem

```
iou3d.obj : error LNK2001: 无法解析的外部符号 "public: long * __cdecl at::Tensor::data<long>(void)const " (??$data@J@Tensor@at@@QEBAPEAJXZ)
build\lib.win-amd64-3.6\iou3d_cuda.cp36-win_amd64.pyd : fatal error LNK1120: 1 个无法解析的外部命令
error: command 'C:\\Program Files (x86)\\VC\\BIN\\x86_amd64\\link.exe' failed with exit status 1120
```

Anyone know how to solve it?

**Comment by candisjesus** [comment]
I guess it's because in Linux, unsigned long == 64 bits, in windows, unsigned long == 32 bits, so u can change all the definition of at::tensor:: data to "unsigned long long" which is 64 bits. Try if u can solve it

**Comment by lonely7yk** [comment]
@candisjesus  Thank you for your reply! However, there is no "at::tensor::data" in the codes that I want to compile(iou3d.cpp, iou3d_kernel.cu). I still have no idea how to deal with it.

**Comment by candisjesus** [comment]
I mean try to change long * keep_data = keep.data<long>();

To 

Long long * keep_data = keep.data<long long>();




U need to change “keep.data”to <long long >



| |
李晶津
邮箱：candisking@126.com
|

签名由 网易邮箱大师 定制

On 09/11/2019 15:19, lonely7yk wrote:

@candisjesus Thank you for your reply! However, there is no "at::tensor::data" in the codes that I want to compile(iou3d.cpp, iou3d_kernel.cu). I still have no idea how to deal with it.

**Comment by lonely7yk** [comment]
@candisjesus Wow! It works! I have been suffered from the problem for two days. Thank you very much!!

**Comment by Baboom-l** [comment]
> @candisjesus Wow! It works! I have been suffered from the problem for two days. Thank you very much!!

Hi! I want to implement pointrcnn on Windows. Can you give me some advice？

**Comment by gehadza** [comment]
@lonely7yk  I appled Long long * keep_data = keep.data<long long>(); but give me the same error


roipool3d.obj : error LNK2001: unresolved external symbol "public: long * __cdecl at::Tensor::data_ptr<long>(void)const " (??$data_ptr@J@Tensor@at@@QEBAPEAJXZ)
build\lib.win-amd64-cpython-39\roipool3d_cuda.cp39-win_amd64.pyd : fatal error LNK1120: 1 unresolved externals
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\link.exe' failed with exit code 1120
