### ISSUE TITLE
How to generate plane files?

### ISSUE THREAD

**Issue by zhby99** [sshaoshuai/PointRCNN#12]
Hi, Thanks for sharing!

I encountered the following problem when running the first stage training without downloading your plane files.
`FileNotFoundError: [Errno 2] No such file or directory: ../data/KITTI/object/training/planes/005957.txt'`

Can I know how do you get these plane files? btw, how can we turn off the augmentation option so that we can run the code without downloading the plane files?

Thanks!

**Comment by sshaoshuai** [comment]
I have provided the links to download : [road planes](https://drive.google.com/file/d/1d5mq0RXRnvHPVeKx6Q612z0YRO1t2wAp/view)
You could try to turn off the GT augmentation by setting the yaml file:  GT_AUG_ENABLED=True

**Comment by zhby99** [comment]
> I have provided the links to download : [road planes](https://drive.google.com/file/d/1d5mq0RXRnvHPVeKx6Q612z0YRO1t2wAp/view)
> You could try to turn off the GT augmentation by setting the yaml file: GT_AUG_ENABLED=True

Thanks for your reply, and sorry for not making it clear for my first question, that how do you generate these ground files(by what algorithm)?

**Comment by sshaoshuai** [comment]
Sorry for the late reply. 
I didn't implement the ground plane estimation algorithm, and I just copy the ground plane results from some other library (I forget which library and didn't find it when I tries to search it once again, may be 3DOP or MV3D series), and it may be generated by RANSAC based methods. 
The ground plane is just for GT sampling augmentation, and it also almost doesn't affect the final results much.

**Comment by xmyqsh** [comment]
@sshaoshuai 
I got the following result with default hyper-parameters without the `ground plane sampling augmentation` by setting `GT_AUG_ENABLED=False`:
```
bbox AP:89.4665, 88.3059, 88.0492
bev  AP:89.0083, 85.8226, 83.7948
3d   AP:84.4288, 75.6058, 72.7560
aos  AP:89.45, 87.99, 87.59
```

Any hints to improve the results?

**Comment by kangpl** [comment]
@xmyqsh @sshaoshuai 
Hi how do you train the model without the `ground plane sampling augmentaion`, I mean for the first stage training rpn, we set the `DT_AUG_ENABLED=False`, and for the second stage training rcnn, how to train without gt_aug, does it means we should use online augmentation to train the model? Thanks.

**Comment by NonaryR** [comment]
@kangpl hello! did you figured this out?

**Comment by BAI-Yeqi** [comment]
@zhby99 Hi, if you still need the answer, here is what I have found out:

plane data source: [GitHub - kujason/avod: Code for 3D object detection for autonomous driving](https://github.com/kujason/avod) 

the physical meaning of the road planes:

[Planes · Issue #86 · kujason/avod](https://github.com/kujason/avod/issues/86) 

[planes for test · Issue #90 · kujason/avod](https://github.com/kujason/avod/issues/90)
