### ISSUE TITLE
How to train on a custom dataset ? 

### ISSUE THREAD

**Issue by jediofgever** [sshaoshuai/PointRCNN#127]
Hello and thank for releasing the code. 
I have created a plugin under gazebo simulator, which can provide me artificial pointcloud dataset of various  objects. Now I would like to use PointRCNN to train model for an specific object. I can write a dataset similar to KITTI but I am a little confused about how the place the labels. in Original KITTI the 3D box labels are in camera frame however I do not want to use labels in camera frame, I want to directly use frame of point cloud source(x:forward, y:left, z:upright), at which part of code are you transfroming the labels from cam frame to velodyne frame ? 

Also is there any tips or recommendations from you for this task ? 

Thank you for your help

**Comment by mojoee** [comment]
Any update on this issue? I would also like to use another dataset.

**Comment by liulingfeng123** [comment]
> Hello and thank for releasing the code.
> I have created a plugin under gazebo simulator, which can provide me artificial pointcloud dataset of various objects. Now I would like to use PointRCNN to train model for an specific object. I can write a dataset similar to KITTI but I am a little confused about how the place the labels. in Original KITTI the 3D box labels are in camera frame however I do not want to use labels in camera frame, I want to directly use frame of point cloud source(x:forward, y:left, z:upright), at which part of code are you transfroming the labels from cam frame to velodyne frame ?
> 
> Also is there any tips or recommendations from you for this task ?
> 
> Thank you for your help

我想向您请教一些问题，不知道可不可以加以下您的联系方式
