### ISSUE TITLE
undefined symbol when try to run eval_rcnn.py

### ISSUE THREAD

**Issue by stomachacheGE** [sshaoshuai/PointRCNN#13]
Hi,
I installed all the required packages inside a conda env and run build_and_install.sh successfully without any error. However, when I try to run the eval_rcnn.py script, it has the following error:

```
$ python tools/eval_rcnn.py --cfg_file cfgs/default.yaml --ckpt PointRCNN.pth --batch_size 1 --eval_mode rcnn --set RPN.LOC_XZ_FINE False
Traceback (most recent call last):
  File "tools/eval_rcnn.py", line 7, in <module>
    from lib.net.point_rcnn import PointRCNN
  File "/home/xxx/projects/pointrcnn_pytorch/tools/../lib/net/point_rcnn.py", line 3, in <module>
    from lib.net.rpn import RPN
  File "/home/xxx/projects/pointrcnn_pytorch/tools/../lib/net/rpn.py", line 4, in <module>
    from lib.rpn.proposal_layer import ProposalLayer
  File "/home/xxx/projects/pointrcnn_pytorch/tools/../lib/rpn/proposal_layer.py", line 6, in <module>
    import lib.utils.iou3d.iou3d_utils as iou3d_utils
  File "/home/xxx/projects/pointrcnn_pytorch/tools/../lib/utils/iou3d/iou3d_utils.py", line 2, in <module>
    import iou3d_cuda
ImportError: /home/xxx/anaconda2/envs/pointrcnn_pytorch/lib/python3.6/site-packages/iou3d-0.0.0-py3.6-linux-x86_64.egg/iou3d_cuda.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2at19UndefinedTensorImpl10_singletonE
```
Do you have any idea how to deal with it?

**Comment by sshaoshuai** [comment]
It seems you should "import torch" before "import iou3d_cuda", but there is "import torch" in my original iou3d_utils.py, did you change the related codes?

**Comment by stomachacheGE** [comment]
> It seems you should "import torch" before "import iou3d_cuda", but there is "import torch" in my original iou3d_utils.py, did you change the related codes?

Hi, thanks for your quick reply. I got it working by uninstalling and re-installing pytorch. It seems like that I installed the wrong pytorch version at the first time.

*For people who want to know the reason for the error*:

For some reason, when I installed pytorch, it was complied with flag GLIBCXX_USE_CXX11_ABI=1, but the cpp_extension was complied with GLIBCXX_USE_CXX11_ABI=0(you can find this GCC flag when run `bash build_and_install.sh`). This makes the complied extension not compatible with pytorch. 

*reference*: https://discuss.pytorch.org/t/undefined-symbol-when-import-lltm-cpp-extension/32627/4

**Comment by YuanGao19** [comment]
> > It seems you should "import torch" before "import iou3d_cuda", but there is "import torch" in my original iou3d_utils.py, did you change the related codes?
> 
> Hi, thanks for your quick reply. I got it working by uninstalling and re-installing pytorch. It seems like that I installed the wrong pytorch version at the first time.
> 
> _For people who want to know the reason for the error_:
> 
> For some reason, when I installed pytorch, it was complied with flag GLIBCXX_USE_CXX11_ABI=1, but the cpp_extension was complied with GLIBCXX_USE_CXX11_ABI=0(you can find this GCC flag when run `bash build_and_install.sh`). This makes the complied extension not compatible with pytorch.
> 
> _reference_: https://discuss.pytorch.org/t/undefined-symbol-when-import-lltm-cpp-extension/32627/4

Hi and sorry to bother, do you remember the command you used for re-installing pytorch? I can't install pytorch 1.0.0 through "conda install pytorch==1.0.0 torchvision==0.2.1 cuda100 -c pytorch" (PackagesNotFoundError). When I removed "-c pytorch", I can only get a version with GLIBCXX_USE_CXX11_ABI=1...
