### ISSUE TITLE
Calibration mismatch when using the Kitti raw dataset

### ISSUE THREAD

**Issue by tareeqav** [sshaoshuai/PointRCNN#132]
Many thanks for the excellent code in the repository, and the great contribution of your research! It's very educational and informative to read through your paper and code.

I can successfully run your code against the KITTI object test set.  I also imported some of your code into my repository and maintained your commit ID and history so that it's only "borrowing" your code.

- https://github.com/tareeq-av/tareeqav/graphs/contributors
- https://github.com/tareeq-av/tareeqav/tree/master/python/stage1/perception
- https://github.com/tareeq-av/tareeqav/blob/master/python/stage1/demo_pipeline.py

As you know, the KITTI raw dataset uses a different calibration syntax and files for the rotation and translation matrices.

When I attempt to create your calibration object from the raw dataset, the [get_valid_flag](https://github.com/tareeq-av/tareeqav/blob/master/python/stage1/sampledata.py#L230) method seems to reject all of the points, which leads me to believe that:

1. Either I have miss understanding on how to create your calibration objects from the raw calibration files as I have done [here](https://github.com/tareeq-av/tareeqav/blob/master/python/stage1/sampledata.py#L175)
2. There's some other misunderstanding on my part that I am not yet sure what it maybe

Is there any reason why your network would not work on the raw dataset? Are there configs in the `config.py` or `default.yml` that maybe causing this?

 When I run the code I "borrowed" from you repo against a test set sample image and calibration, it works fine, which further leads me to believe its a calibration mismatch

**Comment by godspeed1989** [comment]
The format of the calibration file for raw data and object detection is quite different.
You should be very careful.
May be print both to see the differences?

**Comment by tareeqav** [comment]
@godspeed1989 I agree they are different, but based on this [README](https://github.com/pratikac/kitti/blob/master/readme.raw.txt#L179) from the development kit, the `P_rect_02` should be equivalent to the `P2` from the train/test split.

I still to need to review this again though.  Any thoughts on this?

**Comment by tareeqav** [comment]
@godspeed1989 I finally had more info.  Reading the dev kit of the object dataset, they say:

```
In order to allow the usage of the laser point clouds, gps data, the right
camera image and the grayscale images for the TRAINING data as well, we
provide the mapping of the training set to the raw data of the KITTI dataset.

This information is saved in mapping/train_mapping.txt and train_rand.txt:
```

So I mapped one image from the train set to the raw dataset, and found that in the calibration files, the order of the matrices for velo_to_cam is very different.  Example from sample `000031`:

```
Tr_velo_to_cam: 7.533745000000e-03 -9.999714000000e-01 -6.166020000000e-04 -4.069766000000e-03 1.480249000000e-02 7.280733000000e-04 -9.998902000000e-01 -7.631618000000e-02 9.998621000000e-01 7.523790000000e-03 1.480755000000e-02 -2.717806000000e-01
```
Where are in the raw dataset, if I simply append `T` to `R` it looks like:
```
7.533745e-03 -9.999714e-01 -6.166020e-04 1.480249e-02 7.280733e-04 -9.998902e-01 9.998621e-01 7.523790e-03 1.480755e-02 -4.069766e-03 -7.631618e-02 -2.717806e-01
```
The third element in that matrix is begins to be different.  So I need to think carefully about how to construct `Tr_velo_to_cam` from __R__ and __T__ .

**Comment by tareeqav** [comment]
I was able to solve this be joining the __R__ and __T__ matrices from the __velo_to_cam.txt__ file in the correct way.  Closing issue

**Comment by enting8696** [comment]
I'm sorry I didn't catch your point
So how to change the txt file format in calib (from kitti raw data)
What you say the correct way
