### ISSUE TITLE
Assert error when training on the pseudo-lidar data

### ISSUE THREAD

**Issue by zhyjiang** [sshaoshuai/PointRCNN#150]
Thanks for your fantastic work. I've tried your pre-trained PointRCNN model on the pseudo-lidar data(Generate depth map by PSMNet and convert that into point cloud) of the KITTI dataset and got a pretty good result.

Thus, I want to fine-tune the model on the pseudo-lidar dataset. However, there is an assert error during the training of the RCNN part.

File "/home/haha/ObjectDetection/PointRCNN/tools/../lib/rpn/proposal_layer.py", line 92, in distance_based_proposal
    assert i == 2, '%d' % i
AssertionError: 1

It seems like that the RPN detects nothing even in the first ROI(Is this understanding correct?). Did anyone else meet this problem before?

**Comment by louxy126** [comment]
hi，Has your problem been solved? 老哥你的问题解决了吗？我也遇到了这个错误

**Comment by zhyjiang** [comment]
We switched to another method for 3D object detection. 我们换别的方法了

**Comment by zx970505** [comment]
> hi，Has your problem been solved? 老哥你的问题解决了吗？我也遇到了这个错误

assert len(cfg_list) % 2 == 0
AssertionError

你好,你的这个问题解决了吗

**Comment by desailuoke** [comment]
能提供一下运行的环境吗？我现在跑不起来，头疼

**Comment by yang-jiaye** [comment]
same problem
