### ISSUE TITLE
the output of rpn_reg_layer  does not match the comments

### ISSUE THREAD

**Issue by tsbiosky** [sshaoshuai/PointRCNN#18]
in the rpn_reg_layer the last layer is (conv): Conv1d(128, 52, kernel_size=(1,), stride=(1,)), but why in the comments the discription of rpn_reg is (B,N,8) ,how did this 8 come from? Thanks

**Comment by sshaoshuai** [comment]
I didn't see the (B, N, 8)...
If there is any, it may refer to (dx, dy, dz, dh, dw, dl, cos(ry), sin(ry)).
