### ISSUE TITLE
Can this code run in pytorch0.4?

### ISSUE THREAD

**Issue by wyjforwjy** [sshaoshuai/PointRCNN#19]
Can this code run in pytorch0.4?

**Comment by sshaoshuai** [comment]
Yes, I tested it in pytorch 0.4 before. But I didn't test it recently, you could have a try.

**Comment by wyjforwjy** [comment]
OK.Thank you very much~~

Shaoshuai Shi <notifications@github.com> 于2019年5月7日周二 下午11:09写道：
