### ISSUE TITLE
compile iou3d on windows10

### ISSUE THREAD

**Issue by HelloRicky123** [sshaoshuai/PointRCNN#205]
Thanks to others' answers, I successfully compile iou3d on Windows10. I write this issure for ohters information.

1. environment
`windows10, visual studio 2017, MSVC14.16.27023`
    
2. adjustment

- 2.1. change the two line, according to https://stackoverflow.com/questions/33423502/expression-did-not-evaluate-to-a-constant-c

` unsigned long long* remv_cpu = new unsigned long long[col_blocks];
  // unsigned long long remv_cpu[col_blocks];`

- 2.2. change the two line, according to https://github.com/sshaoshuai/PointRCNN/issues/103
`// const float EPS = 1e-8; 
#define EPS 1e-8`

- 2.3 change this, https://github.com/sshaoshuai/PointRCNN/issues/103
`    // long * keep_data = keep.data<long>();
    long long * keep_data = keep.data<long long>();`

**Comment by gehadza** [comment]
Please, i have a problem when execute roipool3d on windows10 

iou3d.obj : error LNK2001: 无法解析的外部符号 "public: long * __cdecl at::Tensor::data<long>(void)const " (??$data@J@Tensor@at@@QEBAPEAJXZ)
build\lib.win-amd64-3.6\iou3d_cuda.cp36-win_amd64.pyd : fatal error LNK1120: 1 个无法解析的外部命令
error: command 'C:\\Program Files (x86)\\VC\\BIN\\x86_amd64\\link.exe' failed with exit status 1120

**Comment by gehadza** [comment]
![image](https://user-images.githubusercontent.com/20877311/213582010-5b8cef67-5b0f-4320-9f6f-6834a0cfb3ed.png)
