### ISSUE TITLE
Can't open build_and_install.sh

### ISSUE THREAD

**Issue by FOURIERWANG** [sshaoshuai/PointRCNN#21]
Thank you for your answer, I am following the steps on github, however，when I do this:Build and install the pointnet2_lib, iou3d, roipool3d libraries by executing the following command:
sh build_and_install.sh
The result is: Can't open build_and_install.sh
I try some methods,but it is not useful.
Could you offer me some advices?

**Comment by sshaoshuai** [comment]
It seems it's the problem of your environment, and I have no idea about it. Maybe you should try to open it firstly.
