### ISSUE TITLE
What't the function of 'images' in training model using PointRCNN?

### ISSUE THREAD

**Issue by OrangeSodahub** [sshaoshuai/PointRCNN#213]
Hello, here I want to train a model using PointRCNN but I only have pointclouds and labels files. And I occured this while training:
```
2022-04-25 12:35:12,630   INFO  **********************Start training**********************
epochs:   0%|                                           | 0/10 [00:01<?, ?it/s]
train:   0%|                                            | 0/26 [00:00<?, ?it/sTraceback (most recent call last):                                              
  File "train_rcnn.py", line 243, in <module>
    trainer.train(
```
```
    assert os.path.exists(img_file)
AssertionError
```
Is anyone could tell me why images dataset is required during this process? What's more, 'calib' file is also necessary for training but why? PointRCNN train models using only pointcloud data, right?

**Comment by gehadza** [comment]
Hi! I want to implement pointrcnn on Windows? how to do this please I follow the instruction but this error appear "error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2"  when run execute build_and_install.sh on WIN10?
