### ISSUE TITLE
implement pointrcnn on Windows? 

### ISSUE THREAD

**Issue by gehadza** [sshaoshuai/PointRCNN#220]
Hi! I want to implement pointrcnn on Windows? how to do this please I follow the instruction but this error appear "error: command 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe' failed with exit code 2" when run execute build_and_install.sh on WIN10?

**Comment by OrangeSodahub** [comment]
@gehadza This error is because of the cpp interprater on windows (MSVC), you should use gcc like on linux, mac

**Comment by OrangeSodahub** [comment]
The error log, you haven't posted it, how can we know where the compiling error lies?

**Comment by gehadza** [comment]
@OrangeSodahub ![image](https://user-images.githubusercontent.com/20877311/213572712-c5daa0e7-60bb-4b8a-9425-1a3cbedafa8b.png)

**Comment by Weaam20** [comment]
> Hi! I want to implement pointrcnn on Windows? how to do this please I follow the instruction but this error appear "error: command 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe' failed with exit code 2" when run execute build_and_install.sh on WIN10?

Could you tell me how you fixed the problem
