### ISSUE TITLE
FIleNotFoundError: /tools/train_utils/train_utils.py

### ISSUE THREAD

**Issue by zjx99** [sshaoshuai/PointRCNN#23]
python eval_rcnn.py --cfg_file cfgs/default.yaml --ckpt PointRCNN.pth --batch_size 1 --eval_mode rcnn --set RPN.LOC_XZ_FINE False

**Comment by zjx99** [comment]
Hi,  Shaoshuai,
I got a problem when I tried to run the command in quick demo part to evaluate the pretrained model:

_**Traceback (most recent call last):
  File "eval_rcnn.py", line 902, in <module>
    eval_single_ckpt(root_result_dir)
  File "eval_rcnn.py", line 762, in eval_single_ckpt
    load_ckpt_based_on_args(model, logger)
  File "eval_rcnn.py", line 719, in load_ckpt_based_on_args
    train_utils.load_checkpoint(model, filename=args.ckpt, logger=logger)
  File "/home/b70379409/PointRCNN/tools/../tools/train_utils/train_utils.py", line 90, in load_checkpoint
    raise FileNotFoundError
FileNotFoundError**_

I ran the code in the folder tools.
Can you give me any clues? Thank you very much.
Jiaxing

**Comment by lanbo3011** [comment]
Have you solved the problem? I had the same problem.
