### ISSUE TITLE
Segment error: with 'python generate_gt_database.py --class_name 'Car' --split train'

### ISSUE THREAD

**Issue by NLCharles** [sshaoshuai/PointRCNN#25]
It is observed that when running generate_gt_database.py in directory ../PointRCNN/tools, segment error occurs. After printing statement test, I found that error is raised in line 72,

_boxes_pts_mask_list = roipool3d_utils.pts_in_boxes3d_cpu(torch.from_numpy(pts_rect), torch.from_numpy(gt_boxes3d))_

I have no idea why python didn't solve the memory problem. Very weird.

**Comment by NLCharles** [comment]
Correction: the line is 70 in original file after I removed test printings in my file.

**Comment by sshaoshuai** [comment]
```roipool3d_utils.pts_in_boxes3d_cpu()``` uses a customed cpu operation ```pts_in_boxes3d_cpu()``` (path PointRCNN/lib/utils/roipool3d/roipool3d_utils.py). 
So maybe it's due to the inconsistent of your gcc and pytorch version. 
I have tested it with gcc 5.4 and pytorch 1.0.

**Comment by NLCharles** [comment]
Dear Shaoshuai,
I seem to resolve this problem by reinstalling pytorch with the consistent version of gcc(v5.5) and changing my cuda version to 9.0. Thank you for your advice!
