### ISSUE TITLE
gcc cuda version

### ISSUE THREAD

**Issue by FOURIERWANG** [sshaoshuai/PointRCNN#31]
May I post a question?
I configured cuda9.0 cudnn7.2, the corresponding is gcc5.4, but I searched on the Internet and found that gcu6 corresponds to cuda9.0, I want to know what version of cuda cudnn and gcc you use.
Thanks

**Comment by sshaoshuai** [comment]
It's ok, currently I use cuda 9.0, cudnn 7.0, and gcc5.4.

**Comment by DonghunP** [comment]
@sshaoshuai How can I install gcc5.4 version?? It' hard to find reference. There are only 4.9 or 5.5 version of gcc install reference. Thanks ahead.
