### ISSUE TITLE
Recall of RPN stage

### ISSUE THREAD

**Issue by maxjaritz** [sshaoshuai/PointRCNN#33]
Do you have code to do validation during the RPN training? Such as computing recall for proposals or IOU/accuracy for point-wise FG/BG classification every 5 epochs or so? How do you select the checkpoint of RPN training? Do you always take epoch 200?

Thanks

**Comment by sshaoshuai** [comment]
As I said in the readme, you could use the `eval_rcnn.py` with argument `--eval_all` to eval all the checkpoints when you are training or after training. With this argument, the program will detect new checkpoints constantly and eval them if it found a new checkpoint.

**Comment by maxjaritz** [comment]
I see, just use the `--eval_mode rpn`. Thanks!
