### ISSUE TITLE
Question about 'decode_bbox_target'

### ISSUE THREAD

**Issue by 3bobo** [sshaoshuai/PointRCNN#36]
In file `bbox_trainsfrom.py`, the input of `decode_bbox_target` are:

> def decode_bbox_target(roi_box3d, pred_reg, loc_scope, loc_bin_size, num_head_bin, anchor_size, get_xz_fine=True, get_y_by_bin=False, loc_y_scope=0.5, loc_y_bin_size=0.25, get_ry_fine=False):
>     """
>     :param roi_box3d: (N, 7)
>     :param pred_reg: (N, C)
>     :param loc_scope:
>     :param loc_bin_size:
>     :param num_head_bin:
>     :param anchor_size:
>     :param get_xz_fine:
>     :param get_y_by_bin:
>     :param loc_y_scope:
>     :param loc_y_bin_size:
>     :param get_ry_fine:
>     :return:
>     """

however, in `ProposalLayer`, the layer use `decode_bbox_target` to get the proposals:
```
proposals = decode_bbox_target(xyz.view(-1, 3), rpn_reg.view(-1, rpn_reg.shape[-1]),
                                       anchor_size=self.MEAN_SIZE,
                                       loc_scope=cfg.RPN.LOC_SCOPE, 
                                       loc_bin_size=cfg.RPN.LOC_BIN_SIZE, 
                                       num_head_bin=cfg.RPN.NUM_HEAD_BIN, 
                                       get_xz_fine=cfg.RPN.LOC_XZ_FINE, 
                                       get_y_by_bin=False,
                                       get_ry_fine=False)  
```
my question is, why the shape of `roi_box3d` input in definition is   `(N, 7)`, but actual shape of  input is  `(B*N, 3)` ?

**Comment by sshaoshuai** [comment]
Both the RPN stage and the RCNN stage use this function. 
For the RPN stage, the input is the coordinate of foreground points, so it has the shape `(N, 3)`.
For the RCNN stage, the input is the 3D proposals, so it has the shape `(N, 7)` .

**Comment by 3bobo** [comment]
@sshaoshuai  thanks for your explanation
