### ISSUE TITLE
Training log polluted

### ISSUE THREAD

**Issue by maxjaritz** [sshaoshuai/PointRCNN#37]
My training log is polluted with the following:
```
2019-04-19 15:56:56,610  DEBUG  STREAM b'IDAT' 41 8192
2019-04-19 15:56:56,647  DEBUG  STREAM b'IHDR' 16 13
```
This results in a log file of about 70 MB.
Does somebody else have this problem?

**Comment by sshaoshuai** [comment]
You could try to update the level of logging as logging.INFO as follows in the `train.py`:
`logging.basicConfig(level=logging.INFO, format=log_format, filename=log_file)`
