### ISSUE TITLE
Problem in computing the observation angle "alpha" and  rotation angle "ry" ???

### ISSUE THREAD

**Issue by happinesslz** [sshaoshuai/PointRCNN#40]
Thanks! solved!

**Comment by sshaoshuai** [comment]
You wrongly calculate the beta.
In this sample, loc=(3.18, 2.27, 34.38), then
beta = np.arctan2(z, x) = np.arctan2(34.38, 3.18) = 1.4785
alpha = -1.67
Then, "ry = 1* np.pi/2 + (-1.67)-1.4785= -1.5777", which is approximately equal to -1.58.

**Comment by xjjs** [comment]
> You wrongly calculate the beta.
> In this sample, loc=(3.18, 2.27, 34.38), then
> beta = np.arctan2(z, x) = np.arctan2(34.38, 3.18) = 1.4785
> alpha = -1.67
> Then, "ry = 1* np.pi/2 + (-1.67)-1.4785= -1.5777", which is approximately equal to -1.58.

shoudldn't it be "ry=alpha+(beta-pi/2)"?

**Comment by xjjs** [comment]
> You wrongly calculate the beta.
> In this sample, loc=(3.18, 2.27, 34.38), then
> beta = np.arctan2(z, x) = np.arctan2(34.38, 3.18) = 1.4785
> alpha = -1.67
> Then, "ry = 1* np.pi/2 + (-1.67)-1.4785= -1.5777", which is approximately equal to -1.58.

shoudldn't it be "ry=alpha+(beta-pi/2)"?

such as http://hirotaka-hachiya.hatenablog.com/entry/2018/02/10/163432

**Comment by xjjs** [comment]
> You wrongly calculate the beta.
> In this sample, loc=(3.18, 2.27, 34.38), then
> beta = np.arctan2(z, x) = np.arctan2(34.38, 3.18) = 1.4785
> alpha = -1.67
> Then, "ry = 1* np.pi/2 + (-1.67)-1.4785= -1.5777", which is approximately equal to -1.58.

from the data：ry=alpha-θ+pi/2，
but from the image: alpha=ry-θ+pi/2, why there is a difference?
http://hirotaka-hachiya.hatenablog.com/entry/2018/02/10/163432
