### ISSUE TITLE
Why is the angular difference between proposal and ground truth within range of [-pi/4, pi] in orientation refinement

### ISSUE THREAD

**Issue by qiqihaer** [sshaoshuai/PointRCNN#50]
I think this paper is excellent. But I can not understand why the angular difference between proposal and ground truth is within the range [-pi/4, pi] in orientation refinement. I do not know how to infer the range from the assumption that the 3D IoU si at least 0.55.

**Comment by sshaoshuai** [comment]
We could not infer the orientation range from the IoU assumption, and it is just an approximation. Since the 3D IoU 0.55 is strict regarding the orientation [-pi/4, pi/4],  I just clip the orientation to make it within [-pi/4, pi/4], and you could see the code for more details.
