### ISSUE TITLE
Why is this called PointRCNN? what is RCNN here

### ISSUE THREAD

**Issue by Manojbhat09** [sshaoshuai/PointRCNN#54]
I dont see any convolution operation,  hence just curious on what does the name mean.

**Comment by sshaoshuai** [comment]
Actually the shared MLP are implemented by the convolution with kernel size 1x1. Also, PointNet++ is only an alternative backbone for the PointRCNN, and PointRCNN could also use other convolution based backbones to extract point-wise features and adopt our proposed two-stage 3D detection pipeline, which is consistent with the name `PointRCNN`.
