### ISSUE TITLE
A wrong place in the code

### ISSUE THREAD

**Issue by iris0329** [sshaoshuai/PointRCNN#58]
In file `/tools/kitti_object_eval_python/eval.py` line 468,
```
    rets = calculate_iou_partly(dt_annos, gt_annos, metric, num_parts)
```
I think should be :
```
    rets = calculate_iou_partly(gt_annos, dt_annos, metric, num_parts)
```

because you defined : 
```
def calculate_iou_partly(gt_annos, dt_annos, metric, num_parts=50):
```
Am I right ?
Thanks!

**Comment by sshaoshuai** [comment]
The kitti evaluation codes are borrowed from [kitti-object-eval-python](https://github.com/traveller59/kitti-object-eval-python).  
And I think `calculate_iou_partly` is a function to calculate the IoU of two squence of 3D boxes, and the input could be exchangable.

**Comment by iris0329** [comment]
Thanks !
