### ISSUE TITLE
Question about eval_mode

### ISSUE THREAD

**Issue by zl1994** [sshaoshuai/PointRCNN#61]
I wonder why it said in readme that the --eval_mode argument should be consistent with the --train_mode used in the training process. I did't find the difference of rpn_output between rcnn and rcnn_offline during evaluation.

**Comment by sshaoshuai** [comment]
The full model (both two stages) is used in the rcnn mode, while only the stage-2 network is used in the rcnn_offline mode since you have saved the RoIs and features of stage-1 to the files.
