### ISSUE TITLE
ModuleNotFoundError: No module named 'pointnet2_cuda'

### ISSUE THREAD

**Issue by jialeli1** [sshaoshuai/PointRCNN#63]
Hi, when I import the modules installed in build_and_install.sh, I get this error. It seems that the build is not seccussful, but I actually do run $sh build_and_install.sh. Could you give me some tips? Thank you.  

Python 3.6.1 |Anaconda custom (64-bit)| (default, May 11 2017, 13:09:58) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pointnet2_cuda as pointnet2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pointnet2_cuda'
>>> import roipool3d
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'roipool3d'
>>> import iou3d
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'iou3d'
>>>

**Comment by jialeli1** [comment]
when I do this:
cd pointnet2_lib/pointnet2
python setup.py install
I got something strange.

building 'pointnet2_cuda' extension
gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/lijiale/anaconda3/lib/python3.6/site-packages/torch/include -I/home/lijiale/anaconda3/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/lijiale/anaconda3/lib/python3.6/site-packages/torch/include/TH -I/home/lijiale/anaconda3/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda-9.0/include -I/home/lijiale/anaconda3/include/python3.6m -c src/pointnet2_api.cpp -o build/temp.linux-x86_64-3.6/src/pointnet2_api.o -g -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=pointnet2_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/lijiale/anaconda3/lib/python3.6/site-packages/torch/include -I/home/lijiale/anaconda3/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/lijiale/anaconda3/lib/python3.6/site-packages/torch/include/TH -I/home/lijiale/anaconda3/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda-9.0/include -I/home/lijiale/anaconda3/include/python3.6m -c src/ball_query.cpp -o build/temp.linux-x86_64-3.6/src/ball_query.o -g -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=pointnet2_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
/usr/local/cuda-9.0/bin/nvcc -I/home/lijiale/anaconda3/lib/python3.6/site-packages/torch/include -I/home/lijiale/anaconda3/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/lijiale/anaconda3/lib/python3.6/site-packages/torch/include/TH -I/home/lijiale/anaconda3/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda-9.0/include -I/home/lijiale/anaconda3/include/python3.6m -c src/ball_query_gpu.cu -o build/temp.linux-x86_64-3.6/src/ball_query_gpu.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -O2 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=pointnet2_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9220): error: argument of type "const void *" is incompatible with parameter of type "const float *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9231): error: argument of type "const void *" is incompatible with parameter of type "const float *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9244): error: argument of type "const void *" is incompatible with parameter of type "const double *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9255): error: argument of type "const void *" is incompatible with parameter of type "const double *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9268): error: argument of type "const void *" is incompatible with parameter of type "const float *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9279): error: argument of type "const void *" is incompatible with parameter of type "const float *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9292): error: argument of type "const void *" is incompatible with parameter of type "const double *"

**Comment by jialeli1** [comment]
OK, I solved this problem in the following way:
1. Do make sure about your gcc version, it should be gcc4.9 or gcc5.4, plz see this [issue].(https://github.com/sshaoshuai/Pointnet2.PyTorch/issues/1#issuecomment-483575405)
And it's better to keep same gcc version on PyTorch and these extension module compile.
2. Import torch before you import these extension module(pointnet2_cuda, iou3d_cuda and roipool3d_cuda).
Hope these tips will help you.

**Comment by AsmaBRZ** [comment]
I had the same problem using google colab, and this worked for me : 
`egg_path='/usr/local/lib/python3.6/dist-packages/pointnet2-0.0.0-py3.6-linux-x86_64.egg'
sys.path.append(egg_path)
egg_path='/usr/local/lib/python3.6/dist-packages/roipool3d-0.0.0-py3.6-linux-x86_64.egg'
sys.path.append(egg_path)
egg_path='/usr/local/lib/python3.6/dist-packages/iou3d-0.0.0-py3.6-linux-x86_64.egg'
sys.path.append(egg_path)
import pointnet2_cuda
import roipool3d_cuda
import iou3d_cuda`

GCC version :
`Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.5.0-3ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04) `

**Comment by asmabrazi** [comment]
I had the same problem using google colab, and this worked for me :

egg_path='/usr/local/lib/python3.6/dist-packages/pointnet2-0.0.0-py3.6-linux-x86_64.egg' 
sys.path.append(egg_path) 
egg_path='/usr/local/lib/python3.6/dist-packages/roipool3d-0.0.0-py3.6-linux-x86_64.egg'
sys.path.append(egg_path) 
egg_path='/usr/local/lib/python3.6/dist-packages/iou3d-0.0.0-py3.6-linux-x86_64.egg' 
sys.path.append(egg_path) 
import pointnet2_cuda
import roipool3d_cuda 
import iou3d_cuda

GCC version :
Thread model: posix gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)
