### ISSUE TITLE
What is the main obstacle to train PointRCNN end-to-end?

### ISSUE THREAD

**Issue by godspeed1989** [sshaoshuai/PointRCNN#67]
Hi, shaoshuai.
Thanks for your great work.
I am wondering what is the main obstacle to train PointRCNN in an end-to-end style?
Why not implement  Faster-RCNN like roi_pooling to get a canonical RPN's output.
The RoIs are still assigned to each point.
Then, we can construct a pointnet++ style network to refine BBoxes?

**Comment by sshaoshuai** [comment]
Thanks for your interest of our work. 
It simply because I didn't implement the BP function of point cloud pooling at that time. Actually it should be easy to implement this function to support end-to-end training with the this codebase.

**Comment by godspeed1989** [comment]
Thank you. looking forward to the new release soon
