### ISSUE TITLE
ModuleNotFoundError: No module named 'tools.train_utils'

### ISSUE THREAD

**Issue by lonely7yk** [sshaoshuai/PointRCNN#7]
Traceback (most recent call last):
  File "eval_rcnn.py", line 11, in <module>
    import tools.train_utils.train_utils as train_utils
ModuleNotFoundError: No module named 'tools.train_utils'

Hello, I followed the steps in README, while I encountered such problem when I want to use the quick demo. Can you give me any hand? Thanks very much.

**Comment by sshaoshuai** [comment]
Hi, 
I have checked the quick demo steps in several machines and doesn't find any problems.  
Please check your steps and make true you run the command in the path PointRCNN/tools/

**Comment by lonely7yk** [comment]
Thanks for reply very much. It's true that I run the command int the path PointRCNN/tools/, but it doesn't work. 
However, afterwards when I try to change every tools.xx.xx -> xx.xx in tools/eval_rcnn.py, tools/kitti_object_eval_python/eval.py and tools/kitti_object_eval_python/evaluate.py, the command works well.

**Comment by sshaoshuai** [comment]
Glad to hear that!
But I have already add  the root path to the system PATH at _init_path.py file, and the codes should be fine.

**Comment by xjjs** [comment]
Maybe you can solve the problem with the following steps:
1) pip install ~/Download/torch-1.0.0-cp36-cp36m-linux_x86_64.whl （from https://pytorch.org/get-started/previous-versions/, downloaed the pytorch1.0.0 appropriate for cuda10.0）
2) conda install -c numba cudatoolkit=10.0 
3) pip install numpy torchvision==0.2.1 tqdm easydict scipy fire scikit-image numba tensorboardX pyyaml shapely
