### ISSUE TITLE
How to execute build_and_install.sh on WIN10?

### ISSUE THREAD

**Issue by candisjesus** [sshaoshuai/PointRCNN#75]
HEY, thanks a lot for sharing ur coding.
MY question is quite basic, How to execute build_and_install.sh on WIN1O. I have Cuda 10.0, VS2017, gcc 8.1.0, when I try to execute, I met ERROR:
  正在创建库 build\temp.win-amd64-3.7\Release\src\roipool3d_cuda.cp37-win_amd64.lib 和对象 build\temp.win-amd64-3.7\Release\src\roipool3d_cuda.cp37-win_amd64.exp
roipool3d.obj : error LNK2001: 无法解析的外部符号 "public: long * __cdecl at::Tensor::data<long>(void)const " (??$data@J@Tensor@at@@QEBAPEAJXZ)
build\lib.win-amd64-3.7\roipool3d_cuda.cp37-win_amd64.pyd : fatal error LNK1120: 1 个无法解析的外部命令
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\link.exe' failed with exit status 1120

DO I need to install CAFFE?

**Comment by candisjesus** [comment]
I have solved this problem. 
Solution:
open src/ball_query.cpp
change this line: extern THCState *state
to:
THCState *state = at::globalContext().lazyInitCUDA()

**Comment by lonely7yk** [comment]
I changed the code, but the problem still existed.

**Comment by lonely7yk** [comment]
@candisjesus Hi! I want to implement pointrcnn on Windows. Have you got it? Can you leave me some contact information, please?

**Comment by gehadza** [comment]
![image](https://user-images.githubusercontent.com/20877311/213574506-1a9dc0ed-a930-439c-a526-e22d502b00c0.png)
