### ISSUE TITLE
How to compile ..\lib\utils\iou3d and roipool3d

### ISSUE THREAD

**Issue by candisjesus** [sshaoshuai/PointRCNN#76]
I have been trying to compile iou3d and roipool3d, and I met the same problem:
error LNK2001: 无法解析的外部符号 "public: long * __cdecl at::Tensor::data<long>(void)const "
for both of the file.
do I miss some *.lib or *.dll, anyone could offer the solution?
Thanks a lot!!!

**Comment by CodeAunt** [comment]
I got the same error, have you solved it?

**Comment by gehadza** [comment]
I got the same error, have you solved it? @CodeAunt

**Comment by CodeAunt** [comment]
> I got the same error, have you solved it? @CodeAunt

NO. I gave up.
