### ISSUE TITLE
Should I set cfg.RPN.ENABLED to false when train mode is rcnn

### ISSUE THREAD

**Issue by miketry0313** [sshaoshuai/PointRCNN#89]
```
  if args.train_mode == 'rpn':
        cfg.RPN.ENABLED = True
        cfg.RCNN.ENABLED = False
        root_result_dir = os.path.join('../', 'output', 'rpn', cfg.TAG)
    elif args.train_mode == 'rcnn':
        cfg.RCNN.ENABLED = True
        cfg.RPN.ENABLED = cfg.RPN.FIXED = True
```

In above code at `train_rcnn.py`, should I set cfg.RPN.ENABLED to false when train mode is `rcnn`? Thus `kitti_rcnn_dataset` can prepare data to train RCNN.

Thanks for your help.

Mike

**Comment by CarlSchwedes** [comment]
For this you simply need to understand the actual architecture of the PointRCNN network. As it is mentioned in the provided paper on [arXiv](https://arxiv.org/pdf/1812.04244.pdf) and also in the README file, pointrcnn is a **2-stage 3D object detector**. 

**rpn** is the **region proposal network** for **stage-1** where the 3d proposals are generated, while **rcnn** is the is the **2nd-stage** for 3d box and proposal refinement on previously generated proposals from stage-1.


_The  whole  framework  is composed  of  two  stages:   stage-1  for  the  bottom-up  3Dproposal generation and stage-2 for refining proposals inthe canonical coordinates to obtain the final detection re-sults._

_... our  stage-1  sub-network  directly  gen-erates a small number of high-quality 3D proposals frompoint cloud in a bottom-up manner via segmenting the pointcloud of the whole scene into foreground points and back-ground.   The  stage-2  sub-network  transforms  the  pooledpoints of each proposal to canonical coordinates to learnbetter local spatial features, which is combined with globalsemantic features of each point learned in stage-1 for ac-curate  box  refinement  and  confidence  prediction._

So ... training **rcnn** but trying to exclude **rpn-step** doesn't make sense.

**Comment by miketry0313** [comment]
Thanks!
