### ISSUE TITLE
Cannot download calib file from KITTI

### ISSUE THREAD

**Issue by SkyeFromKindergarten** [sshaoshuai/PointRCNN#93]
Hi everyone, there's a tiny problem that I cannot download CALIB file from KITTI. It seems something wrong with the download link KITTI sent to me. Could someone please send "Download camera calibration matrices of object data set (16 MB)" this file to my e-mail? Thanks a lot!

My email: guoyan8833@163.com

Or please tell me how can I solve this download problem.

**Comment by CarlSchwedes** [comment]
wget https://s3.eu-central-1.amazonaws.com/avg-kitti/data_object_calib.zip

**Comment by SkyeFromKindergarten** [comment]
> wget https://s3.eu-central-1.amazonaws.com/avg-kitti/data_object_calib.zip

--2019-08-14 15:50:21--  https://s3.eu-central-1.amazonaws.com/avg-kitti/data_object_calib.zip
Resolving s3.eu-central-1.amazonaws.com (s3.eu-central-1.amazonaws.com)... 31.13.73.17
Connecting to s3.eu-central-1.amazonaws.com (s3.eu-central-1.amazonaws.com)|31.13.73.17|:443... failed: Connection refused.

I think something wrong with their Amazon AWS.

**Comment by CarlSchwedes** [comment]
I didn't experienced any of these problems by downloading the calibration files.

Are you trying to download through any company proxy server?

You can use wget also in combination with proxy settings.

wget -e http_proxy=http://username:password@proxy_host:proxy_port <your_url>

also refer to man-page

**Comment by SkyeFromKindergarten** [comment]
Thanks for your kindly help! Problem solved :)
