### ISSUE TITLE
How to change tolerance of the rcnn model?

### ISSUE THREAD

**Issue by NLCharles** [sshaoshuai/PointRCNN#95]
Dear developers,
I trained the model and it showed good performance. Now I want to decrease the threshold for whatever that lowers the recall rate, making it more tolerable to the object deformation. May you give some advice?

**Comment by CarlSchwedes** [comment]
You can adjust the default configuration, located in tools/cfgs/default.yaml
The score threshold e.g. for car-class is 0.3 in testing
_# config of testing_ 
_SCORE_THRESH: 0.3_

Also define your own parameters in the eval_rcnn.py script to overide _cfg.RCNN.SCORE_THRESH_ to customize your PointRCNN setup
_parser.add_argument('--threshold', dest='threshold', default=0.5, type=float, help='')_

**Comment by NLCharles** [comment]
Thank you! Your tip is indeed appreciated! 
I will close the issue now.
